import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "1",
    name: "Classic Chocolate Cake",
    description: "Rich, moist chocolate cake with dark chocolate ganache and fresh berries",
    price: 45.99,
    image: "/chocolate-ganache-cake.png",
    category: "cakes",
    featured: true,
  },
  {
    id: "2",
    name: "Vanilla Dream Cake",
    description: "Light vanilla sponge with buttercream frosting and edible flowers",
    price: 42.99,
    image: "/vanilla-cake-with-flowers.jpg",
    category: "cakes",
    featured: true,
  },
  {
    id: "3",
    name: "Red Velvet Delight",
    description: "Classic red velvet with cream cheese frosting and white chocolate shavings",
    price: 48.99,
    image: "/red-velvet-cake-cream-cheese.jpg",
    category: "cakes",
    featured: true,
  },
  {
    id: "4",
    name: "Strawberry Shortcake",
    description: "Fresh strawberries layered with whipped cream and fluffy sponge",
    price: 38.99,
    image: "/strawberry-shortcake.jpg",
    category: "cakes",
  },
  {
    id: "5",
    name: "Caramel Drip Cake",
    description: "Salted caramel cake with caramel drip and gold decorations",
    price: 52.99,
    image: "/caramel-drip-cake-gold.jpg",
    category: "cakes",
  },
  {
    id: "6",
    name: "Lemon Blueberry Cake",
    description: "Zesty lemon cake with fresh blueberries and lemon curd filling",
    price: 44.99,
    image: "/lemon-blueberry-cake.jpg",
    category: "cakes",
  },
  {
    id: "7",
    name: "French Croissant",
    description: "Buttery, flaky croissant baked fresh every morning",
    price: 4.99,
    image: "/french-croissant-golden.jpg",
    category: "pastries",
  },
  {
    id: "8",
    name: "Chocolate Eclair",
    description: "Choux pastry filled with vanilla cream and topped with chocolate",
    price: 5.99,
    image: "/chocolate-eclair.png",
    category: "pastries",
  },
  {
    id: "9",
    name: "Fruit Tart",
    description: "Crispy tart shell with pastry cream and seasonal fresh fruits",
    price: 6.99,
    image: "/fruit-tart-fresh-berries.jpg",
    category: "pastries",
  },
  {
    id: "10",
    name: "Macarons Box",
    description: "Assorted French macarons in various flavors (6 pieces)",
    price: 18.99,
    image: "/colorful-french-macarons-box.jpg",
    category: "pastries",
  },
  {
    id: "11",
    name: "Cinnamon Roll",
    description: "Warm cinnamon roll with cream cheese glaze",
    price: 4.49,
    image: "/cinnamon-roll-glaze.jpg",
    category: "pastries",
  },
  {
    id: "12",
    name: "Tiramisu Cup",
    description: "Classic Italian tiramisu with espresso-soaked ladyfingers",
    price: 7.99,
    image: "/tiramisu-dessert-cup.jpg",
    category: "desserts",
  },
]

export const categories = [
  { id: "all", name: "All Products" },
  { id: "cakes", name: "Cakes" },
  { id: "pastries", name: "Pastries" },
  { id: "desserts", name: "Desserts" },
]
